//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace OurBlog.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class blogEntities : DbContext
    {
        public blogEntities()
            : base("name=blogEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<discussinfo> discussinfo { get; set; }
        public DbSet<discussreplyinfo> discussreplyinfo { get; set; }
        public DbSet<doc> doc { get; set; }
        public DbSet<docclass> docclass { get; set; }
        public DbSet<doccls> doccls { get; set; }
        public DbSet<docclsrelation> docclsrelation { get; set; }
        public DbSet<dockeyword> dockeyword { get; set; }
        public DbSet<docstatinfo> docstatinfo { get; set; }
        public DbSet<docstore> docstore { get; set; }
        public DbSet<docwritetimeorder> docwritetimeorder { get; set; }
        public DbSet<filemap> filemap { get; set; }
        public DbSet<foldermap> foldermap { get; set; }
        public DbSet<folderrelationmap> folderrelationmap { get; set; }
        public DbSet<menu> menu { get; set; }
        public DbSet<role> role { get; set; }
        public DbSet<roleauthright> roleauthright { get; set; }
        public DbSet<user> user { get; set; }
        public DbSet<userrole> userrole { get; set; }
        public DbSet<userselfsetting> userselfsetting { get; set; }
        public DbSet<userthirdnomap> userthirdnomap { get; set; }
    }
}
