//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OurBlog.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class blogEntities : DbContext
    {
        public blogEntities()
            : base("name=blogEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<discussinfo> discussinfo { get; set; }
        public DbSet<discussreplyinfo> discussreplyinfo { get; set; }
        public DbSet<doc> doc { get; set; }
        public DbSet<docclass> docclass { get; set; }
        public DbSet<doccls> doccls { get; set; }
        public DbSet<docclsrelation> docclsrelation { get; set; }
        public DbSet<dockeyword> dockeyword { get; set; }
        public DbSet<docstatinfo> docstatinfo { get; set; }
        public DbSet<docstore> docstore { get; set; }
        public DbSet<docwritetimeorder> docwritetimeorder { get; set; }
        public DbSet<filemap> filemap { get; set; }
        public DbSet<foldermap> foldermap { get; set; }
        public DbSet<folderrelationmap> folderrelationmap { get; set; }
        public DbSet<menu> menu { get; set; }
        public DbSet<role> role { get; set; }
        public DbSet<roleauthright> roleauthright { get; set; }
        public DbSet<user> user { get; set; }
        public DbSet<userrole> userrole { get; set; }
        public DbSet<userselfsetting> userselfsetting { get; set; }
        public DbSet<userthirdnomap> userthirdnomap { get; set; }
        public DbSet<discussinfos> discussinfos { get; set; }
        public DbSet<docclassts> docclassts { get; set; }
        public DbSet<docclsrelations> docclsrelations { get; set; }
        public DbSet<docclss> docclss { get; set; }
        public DbSet<dockeywords> dockeywords { get; set; }
        public DbSet<docs> docs { get; set; }
        public DbSet<docstatinfos> docstatinfos { get; set; }
        public DbSet<docstores> docstores { get; set; }
        public DbSet<docwritetimeorders> docwritetimeorders { get; set; }
        public DbSet<filemaps> filemaps { get; set; }
        public DbSet<menus> menus { get; set; }
        public DbSet<roleauthrights> roleauthrights { get; set; }
        public DbSet<roles> roles { get; set; }
        public DbSet<userroles> userroles { get; set; }
        public DbSet<users> users { get; set; }
        public DbSet<userselfsettings> userselfsettings { get; set; }
        public DbSet<userthirdnomaps> userthirdnomaps { get; set; }
    }
}
