//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OurBlog.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class blogEntities : DbContext
    {
        public blogEntities()
            : base("name=blogEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<discussinfo> discussinfo { get; set; }
        public virtual DbSet<discussreplyinfo> discussreplyinfo { get; set; }
        public virtual DbSet<doc> doc { get; set; }
        public virtual DbSet<docclass> docclass { get; set; }
        public virtual DbSet<doccls> doccls { get; set; }
        public virtual DbSet<docclsrelation> docclsrelation { get; set; }
        public virtual DbSet<dockeyword> dockeyword { get; set; }
        public virtual DbSet<docstatinfo> docstatinfo { get; set; }
        public virtual DbSet<docstore> docstore { get; set; }
        public virtual DbSet<docwritetimeorder> docwritetimeorder { get; set; }
        public virtual DbSet<filemap> filemap { get; set; }
        public virtual DbSet<foldermap> foldermap { get; set; }
        public virtual DbSet<folderrelationmap> folderrelationmap { get; set; }
        public virtual DbSet<menu> menu { get; set; }
        public virtual DbSet<role> role { get; set; }
        public virtual DbSet<roleauthright> roleauthright { get; set; }
        public virtual DbSet<user> user { get; set; }
        public virtual DbSet<userrole> userrole { get; set; }
        public virtual DbSet<userselfsetting> userselfsetting { get; set; }
        public virtual DbSet<userthirdnomap> userthirdnomap { get; set; }
    }
}
