//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OurBlog.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class discussreplyinfo
    {
        public long FTopDiscussId { get; set; }
        public int FDiscussLayer { get; set; }
        public System.DateTime FCreateTime { get; set; }
        public long FAuthorId { get; set; }
        public long FReplyUserId { get; set; }
    }
}
