//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace OurBlog.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class discussreplyinfo
    {
        public long FTopDiscussId { get; set; }
        public int FDiscussLayer { get; set; }
        public System.DateTime FCreateTime { get; set; }
        public long FAuthorId { get; set; }
        public long FReplyUserId { get; set; }
    }
}
