//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace OurBlog.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class doc
    {
        public long FDocId { get; set; }
        public System.DateTime FDocCreateTime { get; set; }
        public System.DateTime FDocModifyTime { get; set; }
        public long FAuthorId { get; set; }
        public sbyte FDeleteFlag { get; set; }
        public int FDocTextLength { get; set; }
        public sbyte FPublishFlag { get; set; }
        public sbyte FIsSignature { get; set; }
        public sbyte FCanDiscuss { get; set; }
        public string FDocBriefDescribe { get; set; }
        public string FDocTitle { get; set; }
        public string FSubTitle { get; set; }
    }
}
