//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace OurBlog.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class doccls
    {
        public int FDocCLSID { get; set; }
        public System.DateTime FCREATETIME { get; set; }
        public string FCLSNAME { get; set; }
        public string FCLSDESCRIBE { get; set; }
    }
}
