//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OurBlog.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class foldermap
    {
        public long FFolderId { get; set; }
        public long FParentFolderId { get; set; }
        public int FFileCount { get; set; }
        public string FFolderPath { get; set; }
        public System.DateTime FFolderCreateTime { get; set; }
        public System.DateTime FLastAccessTime { get; set; }
        public System.DateTime FModifyTime { get; set; }
        public string FFolderName { get; set; }
    }
}
