//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace OurBlog.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class foldermap
    {
        public long FFolderId { get; set; }
        public long FParentFolderId { get; set; }
        public int FFileCount { get; set; }
        public string FFolderPath { get; set; }
        public System.DateTime FFolderCreateTime { get; set; }
        public System.DateTime FLastAccessTime { get; set; }
        public System.DateTime FModifyTime { get; set; }
        public string FFolderName { get; set; }
    }
}
