//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace OurBlog.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class menu
    {
        public int FMENUID { get; set; }
        public int FParentMenuId { get; set; }
        public string FMENUNAME { get; set; }
        public string FMENUTIPS { get; set; }
        public string FMENUURL { get; set; }
        public string FMENUSTATUS { get; set; }
        public System.DateTime FCREATETIME { get; set; }
    }
}
