//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace OurBlog.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class userthirdnomap
    {
        public string FOtherNo { get; set; }
        public string FOtherNoDesc { get; set; }
        public string FOtherNoType { get; set; }
        public string FOtherNoUrl { get; set; }
        public long FUserId { get; set; }
    }
}
