//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace OurBlog.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class user
    {
        public long FUSERID { get; set; }
        public string FUSERNO { get; set; }
        public string FUSERNAME { get; set; }
        public string FUSERNICKNAME { get; set; }
        public System.DateTime FUSERREGTIME { get; set; }
        public string FUSERLEVEL { get; set; }
        public Nullable<System.DateTime> FUSERBIRTHDAY { get; set; }
        public string FUSERMOBILENO { get; set; }
        public string FUSERQQNO { get; set; }
        public string FUSERWXID { get; set; }
        public string FUSERMAIL { get; set; }
        public string FUSERSTATUS { get; set; }
        public string FUSERTELNO { get; set; }
        public string FPASSWORD { get; set; }
    }
}
